# Настройки для ядра.
core:
  # Размер датасета (при обучении будет использовано только указанное кол-во, вместо всего датасета).
  dataset_size: 100
  # Кол-во эпох при обучении.
  epochs_count: 500
  # Кол-во примеров из датасета, после которого произойдет обновление весов.
  batch_size: 64

# Настройки для API.
api:
  # Хост.
  host: "0.0.0.0"
  # Порт.
  port: 5000
